{% set name = "mljar-supervised" %}
{% set version = "1.1.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mljar-supervised-{{ version }}.tar.gz
  sha256: 2772b18c99279aa8db98146f0d0923ae04977a4d6534050628725021fdc47974

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - py-xgboost >=1.3.3
    - xgboost >=1.3.3
    - catboost >=0.24.4
    - category_encoders >=2.2.2
    - dtreeviz >=1.3.3
    - joblib >=1.0.1
    - lightgbm >=3.0.0
    - markdown
    - matplotlib-base >=3.2.2
    - numpy >=1.19.5
    - optuna >=2.7.0
    - pandas >=1.2.0
    - scikit-learn >=0.24.2
    - scikit-plot ==0.3.7
    - scipy >=1.6.1
    - seaborn >=0.11.1
    - shap >=0.36.0
    - tabulate >=0.8.7
    - wordcloud >=1.8.1
    - typing-extensions

test:
  imports:
    - supervised
    - supervised.algorithms

about:
  home: https://github.com/mljar/mljar-supervised
  summary: Automated Machine Learning Pipeline with Feature Engineering and Hyper-Parameters Tuning
  description: |
    The mljar-supervised is an Automated Machine Learning Python package that works with tabular data. 
    It is designed to save time for a data scientist. It abstracts the common way to preprocess the data, 
    construct the machine learning models, and perform hyper-parameters tuning to find the best model trophy. 
    It is no black-box as you can see exactly how the ML pipeline is constructed (with a detailed Markdown report for each ML model).
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pplonski
