{% set name = "mljar-supervised" %}
{% set version = "1.1.14" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mljar-supervised-{{ version }}.tar.gz
  sha256: 588cde856656511bf7d3b61d315068d9ca77bf2e17c7c9054da1e6c3a2a29e5f

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - py-xgboost-cpu >=2.0.0
    - catboost >=0.24.4
    - category_encoders >=2.2.2
    - dtreeviz >=2.2.2
    - joblib >=1.0.1
    - lightgbm ==4.3.0
    - markdown
    - matplotlib-base >=3.2.2
    - numpy >=1.26.4,<2
    - optuna-integration >=3.6.0
    - pandas >=2.0.0
    - scikit-learn >=1.5.0
    - mljar-scikit-plot >=0.3.11
    - scipy >=1.6.1
    - seaborn >=0.11.1
    - shap =*=*cpu*
    - tabulate >=0.8.7
    - wordcloud >=1.8.1
    - typing-extensions

test:
  requires:
    - python {{ python_min }}
  imports:
    - supervised
    - supervised.algorithms

about:
  home: https://github.com/mljar/mljar-supervised
  summary: Automated Machine Learning Pipeline with Feature Engineering and Hyper-Parameters Tuning
  description: |
    The mljar-supervised is an Automated Machine Learning Python package that works with tabular data. 
    It is designed to save time for a data scientist. It abstracts the common way to preprocess the data, 
    construct the machine learning models, and perform hyper-parameters tuning to find the best model trophy. 
    It is no black-box as you can see exactly how the ML pipeline is constructed (with a detailed Markdown report for each ML model).
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pplonski
